services:
  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    ports:
      - "6333:6333"
      - "6334:6334"

  neo4j:
    image: neo4j:latest
    container_name: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/reform-william-center-vibrate-press-5829 # Set your desired password
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes # Required for Neo4j images
      # Optional: Configure memory settings
      # - NEO4J_SERVER_MEMORY_HEAP_INITIALSIZE=512M
      # - NEO4J_SERVER_MEMORY_HEAP_MAXSIZE=2G